application: storage-9 
version: 1
runtime: php55
api_version: 1

handlers:

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /(.+\.php).*
  script: \1  

- url: /upload
  script: fileimage.php

- url: /read
  script: read.php